server:
  port: 8080
spring:
  application:
    name: secure-gateway
  security:
    user:
      name: user
      password: password
      roles: USER

# JWT
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJwtTokenGenerationAndValidation123456}
  expiration: 3600000   # 1 hour

# External API client
external:
  api:
    base-url: http://localhost:8080/external/v1   # эмулятор
    connect-timeout: 2000   # 2 sec
    read-timeout: 3000       # 3 sec

# Resilience4j
resilience4j:
  circuitbreaker:
    instances:
      externalApi:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        register-health-indicator: true
  ratelimiter:
    instances:
      externalApi:
        limit-for-period: 5
        limit-refresh-period: 10s
        timeout-duration: 0s   # немедленное отклонение при превышении

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example: DEBUG